config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing'
  get '/about', to: 'static_pages#about'

  namespace :admin do
    root to: "users#index"
    resources :users
    resources :roles, only: %i(index show)
  end

  devise_for :users, skip: %i(sessions registrations passwords)
  devise_scope :user do # Users::SessionsController
    get 'users/sign_in', to: 'users/sessions#new', as:'new_user_session'
    post 'users/sign_in', to: 'users/sessions#create', as:'user_session'
    get 'users/sign_out', to: 'users/sessions#destroy', as:'destroy_user_session'
    delete 'users/sign_out', to: 'users/sessions#destroy'
  end
  devise_scope :user do # Users::RegistrationsController
    get '/users/sign_up', to: 'users/registrations#new', as:'new_user_registration'
    post '/users/sign_up', to: 'users/registrations#create'
    get '/account_settings', to: 'users/registrations#edit', as:'edit_user_registration'
    put '/users/edit', to: 'users/registrations#update', as:'user_registration'
    delete '/users/edit', to: 'users/registrations#destroy'
    delete '/users', to: 'users/registrations#destroy'
    get '/users/cancel', to: 'users/registrations#cancel', as:'cancel_user_registration'
    delete '/users/cancel', to: 'users/registrations#cancel'
  end
  devise_scope :user do # Users::PasswordsController
    get '/users/password/new', to: 'users/passwords#new', as:'new_user_password' # forgot password
    get '/users/password/edit', to: 'users/passwords#edit', as:'edit_user_password'
    patch '/users/password', to: 'users/passwords#update'
    put '/users/password', to: 'users/passwords#update'
  end

  get '/dashboard', to: 'dashboard#show', as: 'dashboard'

  resources :directory_links

  resources :table_options

  concern :hovercardable do
    member do
      get :hovercard
    end
  end

  resources :searches, only: %i(index)

  concern :destroy_attachable do
    delete '/attachments/:signed_id', action: 'destroy_attachment'
  end

  concern :statusable do
    resources :statuses, only: %i(edit update show)
  end
  resources :statuses, only: %i(edit update show)

  concern :exportable do
    get :export
    post :export
  end

  resources :orders, concerns: %i(hovercardable statusable) do
    collection do
      concerns :exportable
    end
    member do
      get :edit_dept
      concerns :destroy_attachable
    end
  end

  concern :orders_scoped do
    resources :orders, only: %i(index new create), defaults: { route_scoped?: true, resource: @scope.frame.dig(:controller) } do
      collection do
        get '/new', to: 'orders#new'
        get '(/:status)', to: 'orders#index'
        concerns :exportable
        patch '/update', to: 'orders/bulk#update'
      end
    end
  end

  resources :purchasers, except: :show do
    concerns :orders_scoped
  end

  resources :vendors, except: :show do
    concerns :orders_scoped
  end

  resources :order_contents, only: %i(show edit update destroy)

  resources :packaging_materials, only: %i(show new edit update destroy), concerns: %i(statusable)

  resources :order_contents, only: %i(show) do
    resources :packaging_materials, controller: 'order_contents/packaging_materials', only: %i(new index create)
  end

  def generate_order_content_packaging_material_types_routes
    %i(new index create).each do |_action_name|
      PackagingMaterial::Packageable::TYPE_NAMES.each do |packaging_material_type|
        type = packaging_material_type.to_s.downcase.singularize

        case _action_name
        when :new
          get "/order_contents/:order_content_id/packaging_materials/#{type.pluralize}/new",
            to: "order_contents/packaging_materials#new",
            as: "new_order_content_packaging_material_#{type.singularize}".to_sym,
            type: type.classify
        when :index
          get "/order_contents/:order_content_id/packaging_materials/#{type.pluralize}",
            to: 'order_contents/packaging_materials#index',
            as: "order_content_packaging_material_#{type.pluralize}".to_sym,
            type: type.classify
        when :create
          post "/order_contents/:order_content_id/packaging_materials/#{type.pluralize}",
            to: "order_contents/packaging_materials#create",
            type: type.classify
        end
      end
    end
  end

  generate_order_content_packaging_material_types_routes
end

app/models/order_content.rb
# == Schema Information
#
# Table name: order_contents
#
#  id                :bigint           not null, primary key
#  box               :string
#  crate             :string
#  pallet            :string
#  other             :string
#  other_description :text
#  order_id          :bigint           not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class OrderContent < ApplicationRecord
  include Packageables, PackageablesEligibility

  belongs_to :order

  validates :packaging_materials, presence: { message: "required" }, unless: -> {
    packaging_materials_error_attribute, packaging_materials_error_type = OrderValidator.packaging_materials_error_attribute, OrderValidator.packaging_materials_error_type

    !order.errors.where(packaging_materials_error_attribute, packaging_materials_error_type).any?
  }, if: :created_after_packaging_materials_implementation_date?

  def self.all_packaging_materials_attributes_pairs
    _all_packaging_materials_attributes_pair = includes(:packaging_materials).map {|_order_content| _order_content.packaging_materials_attributes_pair }
    _all_packaging_materials_attributes_pair
  end
end

app/models/order_content/aggregator.rb
# https://dev.37signals.com/active-record-nice-and-blended/
# https://dev.37signals.com/active-record-nice-and-blended/
# https://dev.37signals.com/active-record-nice-and-blended/


# @events = Timeline::Aggregator.new(Current.person, filter: current_page_by_creator_filter).events

# class Timeline::Aggregator
#   def initialize(person, filter: nil)
#     @person = person
#     @filter = filter
#   end
# end


# @events = Timeline::Aggregator.new(Current.person, filter: current_page_by_creator_filter).events


class OrderContent::Aggregator
  attr_reader :order_content, :packaging_materials

  def initialize(order_content, filter: nil)
    @order_content = order_content
    @packaging_materials = order_content.packaging_materials
    @filter = filter
  end

  def filter
    @filter
  end

  def filter=(filter)
    @filter = filter
  end

  def packaging_material_ids
    packaging_materials.ids
  end

  def filter
    return nil unless format_filter
    return send @filter.to_sym if @filter.to_sym.in? methods
    return send @filter.to_s.pluralize.to_sym if @filter.to_s.pluralize.to_sym.in? methods
    return send @filter.to_s.singularize.to_sym if @filter.to_s.singularize.to_sym.in? methods
  end

  def format_filter
    return false unless @filter

    return true if @filter.to_sym.in? methods
    return true if @filter.to_s.pluralize.to_sym.in? methods
    return true if @filter.to_s.singularize.to_sym.in? methods

    return false
  end

  def where_not_description_blank
    return nil unless format_filter
    filter.where.not(description: [nil, ''])
  end

  def where_description_blank
    return nil unless format_filter
    filter.where(description: [nil, ''])
  end

  def where_descriptions_match(description: nil)
    return nil unless format_filter
    return nil unless where_not_description_blank.exists?

    # grouped_packaging_materials_with_descriptions = where_not_description_blank.select("description").group("description") # NOTE - ONLY GETS DESCRIPTIONS (+ AUTO INCLUDED TYPE)
    return where_not_description_blank.where('lower(description) = ?', description.downcase) unless description.nil?
  end

  def boxes
    order_content.packaging_materials_boxes
  end

  def pallets
    order_content.packaging_materials_pallets
  end

  def crates
    order_content.packaging_materials_crates
  end

  def others
    order_content.packaging_materials_others
  end

  # def ids
  #   filter
  # end

  # private
  #   def event_ids
  #     event_ids_via_optimized_query(1.week.ago) || event_ids_via_optimized_query(3.months.ago) || event_ids_via_regular_query
  #   end
  #
  #   # Fetching the most recent recordings optimizes the query enormously for large sets of recordings
  #   def event_ids_via_optimized_query(created_since)
  #     limit = extract_limit
  #     event_ids = filtered_ordered_recordings.where("recordings.created_at >= ?", created_since).pluck("relays.event_id")
  #     event_ids if event_ids.length >= limit
  #   end
  #
  #   def event_ids_via_regular_query
  #     filtered_ordered_recordings.pluck("relays.event_id")
  #   end
end

app/models/order_content/castable_package_type_fields.rb
module OrderContent::CastablePackageTypeFields
  extend ActiveSupport::Concern

  def has_package_type_amount?(attr_name)
    attr_val = send(attr_name)

    return false if attr_val.nil?
    return false if attr_val.blank?
    return false if attr_val == '0'

    return true
  end

  def has_castable_package_amount?(attr_name)
    attr_val = send(attr_name)

    return true if attr_val.nil?
    return true if attr_val.blank?
    return false if attr_val.count("a-zA-Z") > 0
    return true
  end

  def cast_package_amount_to_i!(attr_name)
    send(attr_name).to_i
  end

  def attr_castable?(attr_name)
    attr_val = send(attr_name)

    return true if attr_val.nil?
    return true if attr_val.blank?
    return false if attr_val.count("a-zA-Z") > 0
    return true
  end
end

app/models/order_content/packageables/describable.rb
module OrderContent::Packageables::Describable
  extend ActiveSupport::Concern

  included do
    def without_descriptions
      where(description: [nil, ''])
    end

    def with_descriptions
      where.not(description: [nil, ''])
    end
  end
end

app/controllers/order_contents/packaging_materials_controller.rb
class OrderContents::PackagingMaterialsController < ApplicationController
  layout "stacked_shell"

  before_action :set_order_content, :set_order, only: %i[ index new create ]

  def index
    packaging_materials =
      if packaging_material_scoped?
        index_types = (params[:type].in? PackagingMaterial::Packageable::TYPE_NAMES) ? params[:type] : PackagingMaterial::Packageable::TYPES
        index_scoped_types = "PackagingMaterial::#{index_types}"

        @order_content.packaging_materials.where(type: index_scoped_types)
      else
        @order_content.packaging_materials
      end
    @packaging_materials = packaging_materials.order(created_at: :desc)
  end

  def new
    if packaging_material_scoped?
      new_scoped_type = ((params[:type].in? PackagingMaterial::Packageable::TYPE_NAMES) ? "PackagingMaterial::#{params[:type]}" : 'PackagingMaterial::Other')

      @packaging_material = PackagingMaterial.new(
        order_content: @order_content,
        type: new_scoped_type,
      )
    else
      @packaging_material = @order_content.packaging_materials.build
    end
  end

  def create
    @packaging_material = PackagingMaterial.new(
      order_content: @order_content,
      type: ((packaging_material_params[:type].in? PackagingMaterial::Packageable::TYPES) ? packaging_material_params[:type] : 'PackagingMaterial::Other'),
      description: packaging_material_params[:description],
    )

    respond_to do |format|
      if @packaging_material.save
        format.html { redirect_to @order, notice: "Packaging material was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_order_content
      @order_content = OrderContent.find(params[:order_content_id])
    end

    def set_order
      @order = @order_content.order
    end

    def packaging_material_scoped?
      params[:type].in? PackagingMaterial::Packageable::TYPE_NAMES
    end

    def packaging_material_params
      packaging_material_from_param = "packaging_material"

      if packaging_material_scoped?
        packaging_material_type_from_params = (params[:type].in? PackagingMaterial::Packageable::TYPE_NAMES) ? params[:type] : 'Other'
        packaging_material_from_param << "_#{packaging_material_type_from_params.downcase}"

        params.require(packaging_material_from_param.to_sym).permit(
          :type,
          :description,
        ).with_defaults(
          order_content_id: @order_content.id,
          type: packaging_material_type_from_params,
        )
      else
        params.require(packaging_material_from_param.to_sym).permit(
          :type,
          :description,
        ).with_defaults(
          order_content_id: @order_content.id,
        )
      end
    end
end

app/controllers/order_contents_controller.rb
class OrderContentsController < ApplicationController
  layout "stacked_shell"

  before_action :set_order_content, :set_order, :set_packaging_materials, only: %i[ show edit update destroy ]

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @order_content.update(order_content_params)
        format.html { redirect_to @order, notice: "Order content updated successfully." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order_content.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  private
    def set_order_content
      @order_content = OrderContent.find(params[:id])
    end

    def set_order
      @order = @order_content.order
    end

    def set_packaging_materials
      # @packaging_materials = @order_content.packaging_materials
      @packaging_materials = @order_content.packaging_materials.order(created_at: :desc)
    end

    def order_content_params
      params.require(:order_content).permit(
        :box, :crate, :pallet, :other, :other_description,
        # images: [],
        packaging_materials_attributes:[
          # :id, :box, :crate, :pallet, :other, :other_description
          :id, :type, :description, :_destroy,
        ]
      )
    end
end

app/views/order_contents/_form.html.erb
<% css_form_label = "inline-block align-middle text-sm font-medium leading-6" %>
<% css_form_text_field = "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
<%= form_with model: order_content, id: "order_content_form" do |form| %>
  <% if form.object.errors.any? %>
    <%= tag.div class: "w-full h-auto mb-6" do %>
      <%= render partial: "/layouts/stacked_shell/headings/form_errors", locals: {
        form: form,
      } %>
    <% end %>
  <% end %>

  <fieldset class="mb-3">
    <div class="mx-auto">
      <%#= render partial: "/packaging_materials/form", locals: {
        order_content_form: local_assigns[:form],
      } %>
    </div>
  </fieldset>
  <%= form.submit "#{order_content.new_record? ? 'Create order content' : 'Save changes' }", class: 'inline-flex hover:cursor-pointer justify-center rounded-md bg-indigo-600 py-2 px-5 text-md font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600' %>
<% end %>

app/views/order_contents/_order_content.html.erb
<span>
  <div class="my-3 mt-2 flex rounded-md shadow-sm">
    <span class="hover:cursor-default inline-flex items-center rounded-l-md border border-r-0 border-gray-300 px-3 text-gray-500 sm:text-sm">Boxes</span>
    <div class="block w-full min-w-0 flex-1 rounded-none rounded-r-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
      <span class="ml-3">
        <%= order_content.box.present? ? order_content.box : '0' %>
      </span>
    </div>
  </div>
  <div class="my-3 mt-2 flex rounded-md shadow-sm">
    <span class="hover:cursor-default inline-flex items-center rounded-l-md border border-r-0 border-gray-300 px-3 text-gray-500 sm:text-sm">Crates</span>
    <div class="block w-full min-w-0 flex-1 rounded-none rounded-r-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
      <span class="ml-3">
        <%= order_content.crate.present? ? order_content.crate : '0' %>
      </span>
    </div>
  </div>
  <div class="my-3 mt-2 flex rounded-md shadow-sm">
    <span class="hover:cursor-default inline-flex items-center rounded-l-md border border-r-0 border-gray-300 px-3 text-gray-500 sm:text-sm">Pallets</span>
    <div class="block w-full min-w-0 flex-1 rounded-none rounded-r-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
      <span class="ml-3">
        <%= order_content.pallet.present? ? order_content.pallet : '0' %>
      </span>
    </div>
  </div>
  <% if order_content.other.present? %>
    <div class="my-3 mt-2 flex rounded-md shadow-sm">
      <span class="inline-flex items-center rounded-l-md border border-r-0 border-gray-300 px-3 text-gray-500 sm:text-sm">Other</span>
      <div class="block w-full min-w-0 flex-1 rounded-none rounded-r-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
        <span class="ml-3">
          <%= order_content.other.present? ? order_content.other : '0' %>
        </span>
      </div>
    </div>
  <% end %>
  <% if order_content && order_content.other_description.present? %>
    <div class="mt-3 mb-2 sm:my-3 mt-2 rounded-md shadow-sm">
      <div class="block w-full text-gray-500 text-sm mb-1 sm:mb-0 sm:leading-9">
        Description:
      </div>
      <div class="block w-full min-w-0 flex-1 rounded-md border-1 border-gray-300 p-3 text-gray-500 text-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
        <span>
          <%= order_content.other_description %>
        </span>
      </div>
    </div>
  <% end %>
</span>

app/views/order_contents/edit.html.erb
<% @page_heading_title = "Editing order content" %>
<% content_for :page_heading_button do %>
  <%= render partial: "/layouts/stacked_shell/headings/buttons/back_btn_with_fallback", locals: {
    fallback_location: @order_content,
    fallback_location_text: "Back to order content",
  } %>
<% end %>
<% content_for :page_heading_card do %>
  <%= turbo_stream.update "card_title", (link_to "Order #{@order.id}", order_path(@order), class:"font-medium text-cyan-700 hover:text-cyan-900") %>
  <%= turbo_stream.update "card_content" do %>
    <div class="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-2">
      <%= render partial: "/application/data_display/stats/overview_card", locals: {
        card_title: "Ship",
        card_description: @order.purchaser.name,
        card_link: (link_to "View Ship", purchaser_orders_path(@order.purchaser), class:"font-medium text-cyan-700 hover:text-cyan-900"),
        card_icon: (render partial: "/layouts/stacked_shell/headings/icons/purchaser"),
      } %>
      <% vendor_data_overview_card_link = (link_to "View Vendor", vendor_orders_path(@order.vendor), class:"font-medium text-cyan-700 hover:text-cyan-900") if authorized_internal_user?  %>
      <% vendor_data_overview_card_link = content_tag(:p, "Vendor", class:"font-medium hover:cursor-default") if !authorized_internal_user? %>
      <%= render partial: "/application/data_display/stats/overview_card", locals: {
        card_title: "Vendor",
        card_description: @order.vendor.name,
        card_link: vendor_data_overview_card_link,
        card_icon: (render partial: "/layouts/stacked_shell/headings/icons/vendor"),
      } %>
    </div>
  <% end %>
<% end %>
<section class="pb-12">
  <div class="sm:flex sm:items-center mb-5 sm:mb-7">
    <div class="sm:flex-auto">
      <div class="text-center sm:text-left">
        <%= tag.h1 'Packaging materials', class: %w( ml-2 text-2xl font-semibold leading-6 text-gray-900 ) %>
        <%= tag.p 'Edit information about the packaging materials recieved below.', class: %w( mt-2 ml-2 mb-1 text-md text-gray-700 ) %>
      </div>
    </div>
  </div>
  <div class="overflow-hidden bg-white rounded-md border border-gray-100 shadow">
    <div class="px-4 py-5 sm:px-6">
      <%# NOTE: EDITING ORDER, NOT ORDER CONTENT (form_with model: @order) is this file necessary??? %>
      <%= form_with model: @order, id: "order_form" do |form| %>
        <%= render partial: '/orders/order_content_fields', locals: {
          form: form,
          order: @order,
          order_content: @order.order_content,
        } %>
        <div class="inline-block flex justify-end">
          <%= form.submit "#{(@order_content.new_record? ? 'Create new order content' : 'Save changes')}", class: 'w-full hover:cursor-pointer justify-center rounded-md bg-indigo-600 py-2 px-5 text-md font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600' %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/order_contents/show.html.erb
<% @page_heading_title = "Order Content" %>
<% content_for :page_heading_button do %>
  <%= render partial: "/layouts/stacked_shell/headings/buttons/animated_edit", locals: {
    link_to_path: edit_order_content_path(@order_content),
    link_to_text: "Edit order content",
  } if authorized_internal_user? %>
  <%= render partial: "/layouts/stacked_shell/headings/buttons/back_btn_with_fallback", locals: {
    fallback_location: @order,
    fallback_location_text: "Back to order",
  } %>
<% end %>
<% content_for :page_heading_card do %>
  <% content_for :order_content_card_title do %>
    <span><%= link_to "Order #{@order.id}", order_path(@order), class: "font-medium text-cyan-700 hover:text-cyan-900" %>'s content</span>
  <% end %>
  <%= turbo_stream.update "card_title", yield(:order_content_card_title) %>
  <div class="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-2">
    <%= render partial: "/application/data_display/stats/overview_card", locals: {
      card_title: "Ship",
      card_description: @order.purchaser.name,
      card_link: (link_to "View Ship", purchaser_orders_path(@order.purchaser), class:"font-medium text-cyan-700 hover:text-cyan-900"),
      card_icon: (render partial: "/layouts/stacked_shell/headings/icons/purchaser"),
    } %>
    <% vendor_data_overview_card_link = (link_to "View Vendor", vendor_orders_path(@order.vendor), class:"font-medium text-cyan-700 hover:text-cyan-900") if authorized_internal_user?  %>
    <% vendor_data_overview_card_link = content_tag(:p, "Vendor", class:"font-medium hover:cursor-default") if !authorized_internal_user? %>
    <%= render partial: "/application/data_display/stats/overview_card", locals: {
      card_title: "Vendor",
      card_description: @order.vendor.name,
      card_link: vendor_data_overview_card_link,
      card_icon: (render partial: "/layouts/stacked_shell/headings/icons/vendor"),
    } %>
  </div>
<% end %>
<span id="order_content_#{@order_content.id}">
  <section class="pb-12">
    <div class="sm:flex sm:items-center mb-5 sm:mb-7">
      <div class="sm:flex-auto">
        <div class="text-center sm:text-left">
          <h1 class="ml-2 text-2xl font-semibold leading-6 text-gray-900">
            Order content
          </h1>
          <p class="mt-2 ml-2 mb-1 text-md text-gray-700">Information about content recieved in the order.</p>
        </div>
      </div>
      <div class="text-center sm:text-right mt-4 sm:mt-0 sm:ml-16 sm:flex-none hover:cursor-pointer">
        <%#= button_to(
          "Bulk edit order content",
          edit_order_content_path(@order_content),
          method: :get,
          class:"btn rounded-md bg-white py-2.5 px-3.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
        ) if authorized_internal_user? %>
      </div>
    </div>
    <div class="overflow-hidden bg-white rounded-md border border-gray-100 shadow">
      <div class="px-4 py-5 sm:px-6">
        <%#= turbo_frame_tag @order_content do %>
          <%= render partial: "/order_contents/order_content", locals: {
            order_content: @order_content,
          } %>
        <%# end %>
      </div>
    </div>
  </section>
</span>
<!-- <span>
  <section class="pb-12">
    <div class="sm:flex sm:items-center mb-5 sm:mb-7">
      <div class="sm:flex-auto">
        <div class="text-center sm:text-left">
          <h1 class="ml-2 text-2xl font-semibold leading-6 text-gray-900">
            Packaging materials
          </h1>
          <p class="mt-2 ml-2 mb-1 text-md text-gray-700">Information about packaging materials recieved in the order.</p>
        </div>
      </div>
      <%#= tag.div class: "text-center sm:text-right mt-4 sm:mt-0 sm:ml-16 sm:flex-none hover:cursor-pointer" do %>
        <%#= button_to(
          "Edit order content",
          edit_order_content_path(@order_content),
          method: :get,
          class:"btn rounded-md bg-white py-2.5 px-3.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
        ) %>
      <%# end %>
    </div>
    <div class="overflow-hidden bg-white rounded-md border border-gray-100 shadow">
      <div class="bg-white rounded-lg shadow pb-5 sm:pb-0">
        <div class="pt-6 flex flex-wrap sm:flex-nowrap justify-center sm:justify-between sm:grid-rows-1 pb-6 border-b">
          <div class="my-3 sm:my-0 mx-3 text-xl sm:text-base font-semibold leading-6 text-gray-900">
            Packaging Materials
          </div>
          <div class="my-3 sm:my-0 mx-3 justify-self-end">
            <%#= link_to 'Add new box', new_order_content_packaging_material_box_path(@order_content), class: "btn btn_outline_indigo" %>
            <%#= link_to 'Add new crate', new_order_content_packaging_material_crate_path(@order_content), class: "btn btn_outline_indigo" %>
            <%#= link_to 'Add new pallet', new_order_content_packaging_material_pallet_path(@order_content), class: "btn btn_outline_indigo" %>
            <%#= link_to 'Add new packaging materials', new_order_content_packaging_material_path(@order_content), class: "btn btn_indigo" %>
          </div>
        </div>
        <div class="mx-4 py-5 sm:mx-6">
          <%#= turbo_frame_tag "packaging_materials", src: order_content_packaging_materials_path(@order_content) do %>
            <%#= tag.p 'Loading packaging materials...' %>
          <%# end %>
        </div>
      </div>
    </div>
  </section>
</span> -->
<span>
  <section class="">
    <div class="sm:flex sm:items-center mb-5 sm:mb-7">
      <div class="sm:flex-auto">
        <div class="text-center sm:text-left">
          <h1 class="ml-2 text-2xl font-semibold leading-6 text-gray-900">
            Packaging materials
          </h1>
          <p class="mt-2 ml-2 mb-1 text-md text-gray-700">Information about packaging materials recieved in the order.</p>
        </div>
      </div>
      <%#= tag.div class: "text-center sm:text-right mt-4 sm:mt-0 sm:ml-16 sm:flex-none hover:cursor-pointer" do %>
        <%#= button_to(
          "Edit order content",
          edit_order_content_path(@order_content),
          method: :get,
          class:"btn rounded-md bg-white py-2.5 px-3.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
        ) %>
      <%# end %>
    </div>
    <div class="overflow-hidden bg-white rounded-md border border-gray-100 shadow">
      <div class="bg-white rounded-lg shadow">
        <div class="pt-6 pb-6 flex flex-wrap sm:flex-nowrap justify-center sm:justify-between sm:grid-rows-1 border-b">
          <div class="my-3 sm:my-0 mx-3 text-xl sm:text-base font-semibold leading-6 text-gray-900">
            Packaging Materials
          </div>
          <div class="my-3 sm:my-0 mx-3 justify-self-end">
            <%= link_to 'Add new box', new_order_content_packaging_material_box_path(@order_content), class: "btn btn_outline_indigo" %>
            <%= link_to 'Add new crate', new_order_content_packaging_material_crate_path(@order_content), class: "btn btn_outline_indigo" %>
            <%= link_to 'Add new pallet', new_order_content_packaging_material_pallet_path(@order_content), class: "btn btn_outline_indigo" %>
            <%= link_to 'Add new packaging materials', new_order_content_packaging_material_path(@order_content), class: "btn btn_indigo" %>
          </div>
        </div>
        <div class="mx-4 py-5 sm:mx-6">
        <%= turbo_frame_tag "packaging_materials", src: order_content_packaging_materials_path(@order_content) do %>
          <%= tag.p 'Loading packaging materials...' %>
        <% end %>
        </div>
      </div>
    </div>
  </section>
</span>