config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing'
  get '/about', to: 'static_pages#about'

  namespace :admin do
    root to: "users#index"
    resources :users
    resources :roles, only: %i(index show)
  end

  devise_for :users, skip: %i(sessions registrations passwords)
  devise_scope :user do # Users::SessionsController
    get 'users/sign_in', to: 'users/sessions#new', as:'new_user_session'
    post 'users/sign_in', to: 'users/sessions#create', as:'user_session'
    get 'users/sign_out', to: 'users/sessions#destroy', as:'destroy_user_session'
    delete 'users/sign_out', to: 'users/sessions#destroy'
  end
  devise_scope :user do # Users::RegistrationsController
    get '/users/sign_up', to: 'users/registrations#new', as:'new_user_registration'
    post '/users/sign_up', to: 'users/registrations#create'
    get '/account_settings', to: 'users/registrations#edit', as:'edit_user_registration'
    put '/users/edit', to: 'users/registrations#update', as:'user_registration'
    delete '/users/edit', to: 'users/registrations#destroy'
    delete '/users', to: 'users/registrations#destroy'
    get '/users/cancel', to: 'users/registrations#cancel', as:'cancel_user_registration'
    delete '/users/cancel', to: 'users/registrations#cancel'
  end
  devise_scope :user do # Users::PasswordsController
    get '/users/password/new', to: 'users/passwords#new', as:'new_user_password' # forgot password
    get '/users/password/edit', to: 'users/passwords#edit', as:'edit_user_password'
    patch '/users/password', to: 'users/passwords#update'
    put '/users/password', to: 'users/passwords#update'
  end

  get '/dashboard', to: 'dashboard#show', as: 'dashboard'

  resources :directory_links

  resources :table_options

  concern :hovercardable do
    member do
      get :hovercard
    end
  end

  resources :searches, only: %i(index)

  concern :destroy_attachable do
    delete '/attachments/:signed_id', action: 'destroy_attachment'
  end

  concern :statusable do
    resources :statuses, only: %i(edit update show)
  end
  resources :statuses, only: %i(edit update show)

  concern :exportable do
    get :export
    post :export
  end

  resources :orders, concerns: %i(hovercardable statusable) do
    collection do
      concerns :exportable
    end
    member do
      get :edit_dept
      concerns :destroy_attachable
    end
  end

  concern :orders_scoped do
    resources :orders, only: %i(index new create), defaults: { route_scoped?: true, resource: @scope.frame.dig(:controller) } do
      collection do
        get '/new', to: 'orders#new'
        get '(/:status)', to: 'orders#index'
        concerns :exportable
        patch '/update', to: 'orders/bulk#update'
      end
    end
  end

  resources :purchasers, except: :show do
    concerns :orders_scoped
  end

  resources :vendors, except: :show do
    concerns :orders_scoped
  end

  resources :order_contents, only: %i(show edit update destroy)

  resources :packaging_materials, only: %i(show new edit update destroy), concerns: %i(statusable)

  resources :order_contents, only: %i(show) do
    resources :packaging_materials, controller: 'order_contents/packaging_materials', only: %i(new index create)
  end

  def generate_order_content_packaging_material_types_routes
    %i(new index create).each do |_action_name|
      PackagingMaterial::Packageable::TYPE_NAMES.each do |packaging_material_type|
        type = packaging_material_type.to_s.downcase.singularize

        case _action_name
        when :new
          get "/order_contents/:order_content_id/packaging_materials/#{type.pluralize}/new",
            to: "order_contents/packaging_materials#new",
            as: "new_order_content_packaging_material_#{type.singularize}".to_sym,
            type: type.classify
        when :index
          get "/order_contents/:order_content_id/packaging_materials/#{type.pluralize}",
            to: 'order_contents/packaging_materials#index',
            as: "order_content_packaging_material_#{type.pluralize}".to_sym,
            type: type.classify
        when :create
          post "/order_contents/:order_content_id/packaging_materials/#{type.pluralize}",
            to: "order_contents/packaging_materials#create",
            type: type.classify
        end
      end
    end
  end

  generate_order_content_packaging_material_types_routes
end

app/controllers/sunset_table_options_controller.rb
class SunsetTableOptionsController < ApplicationController
  before_action :set_table_option, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /table_options or /table_options.json
  def index
    @table_options = current_user.table_options
  end

  # GET /table_options/1 or /table_options/1.json
  def show
  end

  # GET /table_options/new
  def new
    @table_option = TableOption.new
  end

  # GET /table_options/1/edit
  def edit
  end

  # POST /table_options or /table_options.json
  def create
    @table_option = TableOption.new table_option_params
    if @table_option.save
      redirect_to request.referrer, notice: "Table options created successfully."
    else
      redirect_to request.referrer
      @table_option.errors.each do |error|
        flash[:alert] = @table_option.errors.full_messages.map {|message| message}
      end
    end
  end

  # PATCH/PUT /table_options/1 or /table_options/1.json
  def update

    if @table_option.update(table_option_params)
      redirect_to request.referrer, notice: "Table options updated successfully."
    else
      redirect_to request.referrer
      @table_option.errors.each do |error|
        flash[:alert] = @table_option.errors.full_messages.map {|message| message}
      end
    end

  end

  # DELETE /table_options/1 or /table_options/1.json
  def destroy
    @table_option.destroy
    redirect_to request.referrer, notice: "Table options removed. Now displaying default table options"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table_option
      @table_option = TableOption.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def table_option_params
      params.require(:table_option).permit(:resource_table_type, :resource_table_action, :user_id, :resources_per_page, option_list: [])
    end

    def default_table_option_list
      params[:table_option][:set_default_options]
    end
end

app/views/sunset_table_options/_form.html.erb
<%= form_with(model: table_option) do |form| %>

  <!-- <div class="font-bold">
    <%= @resource.controller_name_and_action %>
  </div>


  <div class="font-semibold">
    belongs_to_user? <%= @table_option.belongs_to_user? %>
  </div>

  <div class="font-bold">
    <%= @table_option.inspect %>
  </div> -->

  <div class="field">

    <p class="text-3xl"> <%= "New" if table_option.id.nil? %> <%= ('purchasers' ? 'ships' : "#{controller_name}").titleize.singularize %> Table Options </p>
    <%= form.hidden_field :resource_table_type, value: controller_name.downcase %>
    <%= form.hidden_field :resource_table_action, value: action_name %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%#= form.hidden_field :set_default_options, value: @resource.controller_name_and_action %>
  </div>

  <div class="container bg-gray-200 p-2 ">

    <div class="p-1">
      <p class="text-2xl py-2 -mb-1">
        Columns to Display:
      </p>

      <div class="text-xl">
          <div class="p-2">
            <% strfy_options = TableOptionsHelper.default_table_options_for_form(controller_name_and_action).to_s %>
            <% TableOptionsHelper.default_table_options_for_form(controller_name_and_action).each do | option | %>

                  <% if option.to_s.in? @table_option.option_list %>
                        <div class="p-1">
                          <%= check_box_tag "table_option[option_list][]", option, {:multiple => true} %>
                          <%= option %>
                        </div>
                  <% else  %>
                        <div class="p-1">
                          <%= check_box_tag "table_option[option_list][]", option %>
                          <%= option %>
                        </div>
                  <% end %>

            <% end %>
          </div>

          <div class="py-4">
            <input type="Button" class="btn btn-outline-secondary" onclick="togglecheckboxes('table_option[option_list][]')" value="Select/Unselect All" />
          </div>
      </div>

    <hr>

    <div>
      <p class="text-2xl">
        Amount of <%= ('purchasers' ? 'ships' : "#{controller_name}").titleize %> to display
      </p>
      <div class="text-xl">
        <%= form.select :resources_per_page, options_for_select(TableOptionsHelper.options_for_resources_per_page, @table_option.resources_per_page)  %>
      </div>
    </div>

    <% if @table_option.belongs_to_user? %>
      <div class="px-8">
        <hr>
      </div>
      <div class="pt-2">
      <%= link_to "Remove #{('purchasers' ? 'ships' : "#{controller_name}").titleize} table options", @table_option, method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    <% end %>
  </div>

  <br>
</div>

  <div class="p-4">
    <div class="actions btn btn-outline-primary">
      <%= button_tag(type: 'submit') do %>
        Save
      <% end %>
    </div>
  </div>

<% end %>


<script type="text/javascript">
var isAllCheck = false;
function togglecheckboxes(table_option_cb_array){

  var table_option_cb_array = document.getElementsByName('table_option[option_list][]');
  for(var i = 0; i < table_option_cb_array.length; i++){
      table_option_cb_array[i].checked = !isAllCheck
  }

  isAllCheck = !isAllCheck;
}
</script>

app/views/sunset_table_options/_table_options_modal.html.erb
<!-- Button trigger modal -->
<div class="btn btn-outline-primary" data-toggle="modal" data-target="#tableOptionsModal">
  Table Options: <%= ('purchasers' ? 'ships' : "#{controller_name}").titleize%>
</div>
<div class=" text-gray-500 text-sm pt-2"> (Select what columns are displayed on Table)</div>

<!-- Modal -->
<div class="modal fade" id="tableOptionsModal" tabindex="-1" role="dialog" aria-labelledby="tableOptionsModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="tableOptionsModalLabel">
          Table Options
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% @form_table_option = TableOption.new unless @table_option.belongs_to_user? %>
        <% @form_table_option = @table_option if @table_option.belongs_to_user? %>
        <%= render 'table_options/form', table_option: @form_table_option %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/sunset_table_options/edit.html.erb
<h1>Editing Table Option</h1>

<%= render 'form', table_option: @table_option %>

<%= link_to 'Show', @table_option %> |
<%= link_to 'Back', table_options_path %>

app/views/sunset_table_options/index.html.erb
<% content_for :title, "You have #{current_user.table_options.count} Table Options" %>
<%= render 'shared/under_header_card_options' %>


<div class="card">


  <br>
  <p class="text-xl pt-4">
    Table Options allow you to select what you see on each table.

    <br>
    <br>
      Your changes will only effect your individual account so feel free to customize tables how you like.

      <br>
      <br>
      You can always change your options by clicking the
      <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOptions" aria-expanded="false" aria-controls="collapseOptions" id="tableOptions">
               Options
      </button>
      button which is available on each main page (Orders, Ships, Vendors).
  </p>

  <p class="text-xl p-4">
    The table with the red background has an extra column(date delivered) that may not be useful for you at the moment. does not have a Date Delivered column.
  </p>
    <div class="p-2 justify-content-center  ">

            <div class="p-4 bg-red-100" style="'">
              <div class="p-2 ">
              <div class="text-xl font-bold ">
                Before Table Options:
              </div>
              <br>


              <div class="row justify-content-center">
                <div class="col-auto">

                <table class="table table-responsive table-striped border-2 border-red-200">
                  <thead>
                    <tr>
                      <th scope="col"> Order</th>
                      <th scope="col">Vendor</th>
                      <th scope="col">Date Recieved</th>
                      <th scope="col">Date Delivered</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="row">1</th>
                      <td>Grainger</td>
                      <td>7/4/21</td>
                      <td> 7/7/21</td>
                    </tr>
                    <tr>
                      <th scope="row">2</th>
                      <td>Grainger</td>
                      <td>7/4/21</td>
                      <td> 7/6/21</td>
                    </tr>
                    <tr>
                      <th scope="row">3</th>
                      <td>Good Smoker</td>
                      <td>7/3/21</td>
                      <td> 7/8/21</td>
                    </tr>
                  </tbody>
                </table>

              </div>
             </div>


              </div>

            </div>




            <div class="p-4 bg-green-100" style="'">
              <div class="p-2">
              <div class="text-xl font-bold">
                After Table Options:
              </div>
              <br>
              <div class="row justify-content-center">
                <div class="col-auto">

                <table class="table table-striped  border-2 border-green-200">
                  <thead>
                    <tr>
                      <th scope="col"> Order</th>
                      <th scope="col">Vendor</th>
                      <th scope="col">Date Recieved</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="row">1</th>
                      <td>Grainger</td>
                      <td>7/4/21</td>
                    </tr>
                    <tr>
                      <th scope="row">2</th>
                      <td>Grainger</td>
                      <td>7/4/21</td>
                    </tr>
                    <tr>
                      <th scope="row">3</th>
                      <td>Good Smoker</td>
                      <td>7/6/21</td>
                    </tr>
                  </tbody>
                </table>
              </div>
             </div>


              </div>

            </div>



    </div>





</div>




<h1>Table Options</h1>

<table>
  <thead>
    <tr>
      <th>Resource table type</th>
      <th>Option list</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @table_options.each do |table_option| %>
      <tr>
        <td><%= table_option.resource_table_type %></td>
        <td><%= table_option.option_list %></td>
        <td><%= table_option.user_id %></td>
        <td><%= link_to 'Show', table_option %></td>
        <td><%= link_to 'Edit', edit_table_option_path(table_option) %></td>
        <td><%= link_to 'Destroy', table_option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table Option', new_table_option_path %>

app/views/sunset_table_options/new.html.erb
<h1>New Table Option</h1>

<%= render 'form', table_option: @table_option %>

<%= link_to 'Back', table_options_path %>

app/views/sunset_table_options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Resource table type:</strong>
  <%= @table_option.resource_table_type %>
</p>

<p>
  <strong>Option list:</strong>
  <%= @table_option.option_list %>
</p>

<p>
  <strong>User:</strong>
  <%= @table_option.user_id %>
</p>

<%= link_to 'Edit', edit_table_option_path(@table_option) %> |
<%= link_to 'Back', table_options_path %>