config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing'
  get '/about', to: 'static_pages#about'

  namespace :admin do
    root to: "users#index"
    resources :users
    resources :roles, only: %i(index show)
  end

  devise_for :users, skip: %i(sessions registrations passwords)
  devise_scope :user do # Users::SessionsController
    get 'users/sign_in', to: 'users/sessions#new', as:'new_user_session'
    post 'users/sign_in', to: 'users/sessions#create', as:'user_session'
    get 'users/sign_out', to: 'users/sessions#destroy', as:'destroy_user_session'
    delete 'users/sign_out', to: 'users/sessions#destroy'
  end
  devise_scope :user do # Users::RegistrationsController
    get '/users/sign_up', to: 'users/registrations#new', as:'new_user_registration'
    post '/users/sign_up', to: 'users/registrations#create'
    get '/account_settings', to: 'users/registrations#edit', as:'edit_user_registration'
    put '/users/edit', to: 'users/registrations#update', as:'user_registration'
    delete '/users/edit', to: 'users/registrations#destroy'
    delete '/users', to: 'users/registrations#destroy'
    get '/users/cancel', to: 'users/registrations#cancel', as:'cancel_user_registration'
    delete '/users/cancel', to: 'users/registrations#cancel'
  end
  devise_scope :user do # Users::PasswordsController
    get '/users/password/new', to: 'users/passwords#new', as:'new_user_password' # forgot password
    get '/users/password/edit', to: 'users/passwords#edit', as:'edit_user_password'
    patch '/users/password', to: 'users/passwords#update'
    put '/users/password', to: 'users/passwords#update'
  end

  get '/dashboard', to: 'dashboard#show', as: 'dashboard'

  resources :directory_links

  resources :table_options

  concern :hovercardable do
    member do
      get :hovercard
    end
  end

  resources :searches, only: %i(index)

  concern :destroy_attachable do
    delete '/attachments/:signed_id', action: 'destroy_attachment'
  end

  concern :statusable do
    resources :statuses, only: %i(edit update show)
  end
  resources :statuses, only: %i(edit update show)

  concern :exportable do
    get :export
    post :export
  end

  resources :orders, concerns: %i(hovercardable statusable) do
    collection do
      concerns :exportable
    end
    member do
      get :edit_dept
      concerns :destroy_attachable
    end
  end

  concern :orders_scoped do
    resources :orders, only: %i(index new create), defaults: { route_scoped?: true, resource: @scope.frame.dig(:controller) } do
      collection do
        get '/new', to: 'orders#new'
        get '(/:status)', to: 'orders#index'
        concerns :exportable
        patch '/update', to: 'orders/bulk#update'
      end
    end
  end

  resources :purchasers, except: :show do
    concerns :orders_scoped
  end

  resources :vendors, except: :show do
    concerns :orders_scoped
  end

  resources :order_contents, only: %i(show edit update destroy)

  resources :packaging_materials, only: %i(show new edit update destroy), concerns: %i(statusable)

  resources :order_contents, only: %i(show) do
    resources :packaging_materials, controller: 'order_contents/packaging_materials', only: %i(new index create)
  end

  def generate_order_content_packaging_material_types_routes
    %i(new index create).each do |_action_name|
      PackagingMaterial::Packageable::TYPE_NAMES.each do |packaging_material_type|
        type = packaging_material_type.to_s.downcase.singularize

        case _action_name
        when :new
          get "/order_contents/:order_content_id/packaging_materials/#{type.pluralize}/new",
            to: "order_contents/packaging_materials#new",
            as: "new_order_content_packaging_material_#{type.singularize}".to_sym,
            type: type.classify
        when :index
          get "/order_contents/:order_content_id/packaging_materials/#{type.pluralize}",
            to: 'order_contents/packaging_materials#index',
            as: "order_content_packaging_material_#{type.pluralize}".to_sym,
            type: type.classify
        when :create
          post "/order_contents/:order_content_id/packaging_materials/#{type.pluralize}",
            to: "order_contents/packaging_materials#create",
            type: type.classify
        end
      end
    end
  end

  generate_order_content_packaging_material_types_routes
end

app/views/orders/remix/table/_sticky_condensed_row.html.erb
<% col_css_classes = "whitespace-nowrap px-2 py-2 text-sm" %>

<%# first_col_css_classes = "whitespace-nowrap py-2 pl-4 pr-3 text-sm text-gray-500 sm:pl-0" %>
<%# last_col_css_classes = "relative whitespace-nowrap py-2 pl-3 pr-4 text-right text-sm font-medium sm:pr-0" %>
<% first_col_css_classes = "#{col_css_classes} -px-2 py-2 pl-4 pr-3 sm:pl-0 text-gray-500" %>
<% last_col_css_classes = "relative #{col_css_classes} py-2 -px-2 pl-3 pr-4 text-right font-medium sm:pr-0" %>

<% primary_col_css_classes = "#{col_css_classes} font-medium text-gray-900" %>
<% secondary_col_css_classes = "#{col_css_classes} text-gray-500 cursor-default" %>

<% td_link_css_classes = "text-indigo-600 hover:text-indigo-800" %>

<!-- FIRST COL -->
<td class="<%= first_col_css_classes %>">
    <%= link_to "#{order.id}", order_path(order), class: td_link_css_classes %>
</td>

<td class="<%= secondary_col_css_classes %>">
  <%= order.dept.present? ? order.dept : "n/a" %>
</td>

<td class="<%= primary_col_css_classes %>">
  <%#= link_to "purchaser- #{order.purchaser.name}", purchaser_path(order.purchaser), class: td_link_css_classes %>
  <%= link_to "#{order.purchaser.name}", purchaser_path(order.purchaser), class: td_link_css_classes %>
</td>

<td class="<%= primary_col_css_classes %>">
  <%#= link_to "vendor- #{order.vendor.name}", vendor_path(order.vendor), class: td_link_css_classes %>
  <%= link_to "#{order.vendor.name}", vendor_path(order.vendor), class: td_link_css_classes %>
</td>

<td class="<%= secondary_col_css_classes %>">
  <%= order.po_number %>
</td>

<td class="<%= secondary_col_css_classes %>">
  <%= order.tracking_number %>
</td>

<td class="<%= secondary_col_css_classes %>">
  <%= order.try(:date_recieved) ? order.date_recieved.try(:strftime,"%m/%d/%Y") : ' ' %>
</td>

<td class="<%= primary_col_css_classes %>">
  <% if order.order_content.present? %>
    <% content = order.order_content %>
    <%= link_to order_path(order) do %>
      <span class="<%= td_link_css_classes %>">
        Boxes: <%= content.box.present? ? content.box : "0" %>
        <br>
        Crates: <%= content.crate.present? ? content.crate : "0" %>
        <br>
        Pallets: <%= content.pallet.present? ? content.pallet : "0" %>
        <br>
        Other: <%= content.other.present? ? content.other : "0" %>

        <% if content.other.present? && content.other_description.present?   %>
          <br>
          <div class="inline-block">
            <div class="whitespace-normal">
              <span class="<%= td_link_css_classes %>">Other Desc:</span>
              <span class="text-gray-500">
                <%= content.other_description.length >= 25 ? "#{content.other_description[0..25]...}" : "Description: #{content.other_description}" if content.other_description %>
              </span>
            </div>
          </div>
        <% end %>

      </span>
    <% end %>
  <% end %>
</td>

<td class="<%= secondary_col_css_classes %>">
  <%= order.courrier %>
</td>

<td class="<%= secondary_col_css_classes %>">
  <%= order.try(:date_delivered) ? order.date_delivered.try(:strftime,"%m/%d/%Y") : ' ' %>
</td>

<!-- LAST COL -->
<td class="<%= last_col_css_classes %>">
  <a href="#" class="text-indigo-600 hover:text-indigo-900">Edit<span class="sr-only">, AAPS0L</span></a>
</td>