config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing'
  get '/about', to: 'static_pages#about'

  namespace :admin do
    root to: "users#index"
    resources :users
    resources :roles, only: %i(index show)
  end

  devise_for :users, skip: %i(sessions registrations passwords)
  devise_scope :user do # Users::SessionsController
    get 'users/sign_in', to: 'users/sessions#new', as:'new_user_session'
    post 'users/sign_in', to: 'users/sessions#create', as:'user_session'
    get 'users/sign_out', to: 'users/sessions#destroy', as:'destroy_user_session'
    delete 'users/sign_out', to: 'users/sessions#destroy'
  end
  devise_scope :user do # Users::RegistrationsController
    get '/users/sign_up', to: 'users/registrations#new', as:'new_user_registration'
    post '/users/sign_up', to: 'users/registrations#create'
    get '/account_settings', to: 'users/registrations#edit', as:'edit_user_registration'
    put '/users/edit', to: 'users/registrations#update', as:'user_registration'
    delete '/users/edit', to: 'users/registrations#destroy'
    delete '/users', to: 'users/registrations#destroy'
    get '/users/cancel', to: 'users/registrations#cancel', as:'cancel_user_registration'
    delete '/users/cancel', to: 'users/registrations#cancel'
  end
  devise_scope :user do # Users::PasswordsController
    get '/users/password/new', to: 'users/passwords#new', as:'new_user_password' # forgot password
    get '/users/password/edit', to: 'users/passwords#edit', as:'edit_user_password'
    patch '/users/password', to: 'users/passwords#update'
    put '/users/password', to: 'users/passwords#update'
  end

  get '/dashboard', to: 'dashboard#show', as: 'dashboard'

  resources :directory_links

  resources :table_options

  concern :hovercardable do
    member do
      get :hovercard
    end
  end

  resources :searches, only: %i(index)

  concern :destroy_attachable do
    delete '/attachments/:signed_id', action: 'destroy_attachment'
  end

  concern :statusable do
    resources :statuses, only: %i(edit update show)
  end
  resources :statuses, only: %i(edit update show)

  concern :exportable do
    get :export
    post :export
  end

  resources :orders, concerns: %i(hovercardable statusable) do
    collection do
      concerns :exportable
    end
    member do
      get :edit_dept
      concerns :destroy_attachable
    end
  end

  concern :orders_scoped do
    resources :orders, only: %i(index new create), defaults: { route_scoped?: true, resource: @scope.frame.dig(:controller) } do
      collection do
        get '/new', to: 'orders#new'
        get '(/:status)', to: 'orders#index'
        concerns :exportable
        patch '/update', to: 'orders/bulk#update'
      end
    end
  end

  resources :purchasers, except: :show do
    concerns :orders_scoped
  end

  resources :vendors, except: :show do
    concerns :orders_scoped
  end

  resources :order_contents, only: %i(show edit update destroy)

  resources :packaging_materials, only: %i(show new edit update destroy), concerns: %i(statusable)

  resources :order_contents, only: %i(show) do
    resources :packaging_materials, controller: 'order_contents/packaging_materials', only: %i(new index create)
  end

  def generate_order_content_packaging_material_types_routes
    %i(new index create).each do |_action_name|
      PackagingMaterial::Packageable::TYPE_NAMES.each do |packaging_material_type|
        type = packaging_material_type.to_s.downcase.singularize

        case _action_name
        when :new
          get "/order_contents/:order_content_id/packaging_materials/#{type.pluralize}/new",
            to: "order_contents/packaging_materials#new",
            as: "new_order_content_packaging_material_#{type.singularize}".to_sym,
            type: type.classify
        when :index
          get "/order_contents/:order_content_id/packaging_materials/#{type.pluralize}",
            to: 'order_contents/packaging_materials#index',
            as: "order_content_packaging_material_#{type.pluralize}".to_sym,
            type: type.classify
        when :create
          post "/order_contents/:order_content_id/packaging_materials/#{type.pluralize}",
            to: "order_contents/packaging_materials#create",
            type: type.classify
        end
      end
    end
  end

  generate_order_content_packaging_material_types_routes
end

app/views/layouts/stacked_shell/nav/_desktop.html.erb
<nav id="desktop-nav" class="border-b border-gray-700 bg-gray-800 lg:border-none">
  <div class="mx-auto max-w-7xl px-2 sm:px-4 lg:px-8">
    <div class="relative flex h-16 items-center justify-between lg:border-b lg:border-indigo-400 lg:border-opacity-25">
      <div class="flex items-center px-2 lg:px-0">
        <div class="flex-shrink-0">
          <div class="h-8 w-auto">

            <% navbar_brand_url = user_signed_in? ? dashboard_path : root_path %>
            <%= link_to "LMS", navbar_brand_url, class:"mt-0.5 text-slate-200 hover:text-slate-100 text-lg sm:text-xl lg:text-2xl inline-block h-8 w-auto" %>

          </div>
        </div>
        <div class="hidden lg:ml-10 lg:block">
          <div class="flex space-x-4">

            <% desktop_navigation_resource_css_classes = "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm" %>
            <% desktop_navigation_resource_css_classes_current = "bg-gray-900 text-white rounded-md px-3 py-2 text-sm font-medium" %>

            <%= render partial: "layouts/stacked_shell/nav/resource_links", locals:{
              resource_links_css_classes_current: desktop_navigation_resource_css_classes_current,
              resource_links_css_classes: desktop_navigation_resource_css_classes,
            } %>

          </div>
        </div>
      </div>

      <div class="mx-auto flex flex-1 lg:justify-end lg:ml-6">
        <div class="w-1/3">
          <%= yield :search_bar %>
        </div>
      </div>

      <div class="hidden lg:ml-4 lg:block">
        <div class="flex items-center">
          <div data-controller="visibility" data-visibility-value-toggled="false" class="relative ml-3 flex-shrink-0">
            <div>
              <button type="button"  data-action="visibility#toggleTargets" class="flex rounded-md bg-gray-800 text-sm text-gray-400 border-2 border-gray-400 transition ease-in-out delay-150 hover:scale-105 duration-100 hover:border-slate-100 p-1 hover:text-slate-100 hover:text-md focus:ring-1 focus:ring-slate-200 focus:ring-offset-slate-100" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                <span class="sr-only">Open user menu</span>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                </svg>
              </button>
            </div>
            <!--
              Dropdown menu, show/hide based on menu state.
              Entering: "transition ease-out duration-100"
                From: "transform opacity-0 scale-95"
                To: "transform opacity-100 scale-100"
              Leaving: "transition ease-in duration-75"
                From: "transform opacity-100 scale-100"
                To: "transform opacity-0 scale-95"
            -->
            <div data-visibility-target="hideable" hidden class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">

              <% profile_dropdown_navigation_css_classes = "block py-2 px-4 text-sm text-gray-500 hover:text-gray-600 hover:bg-slate-50" %>
              <% profile_dropdown_navigation_css_classes_current = "block py-2 px-4 text-sm text-gray-600 font-medium bg-slate-100" %>

              <%= render partial: "layouts/stacked_shell/nav/user_links", locals:{
                user_links_css_classes_current: profile_dropdown_navigation_css_classes_current,
                user_links_css_classes: profile_dropdown_navigation_css_classes,
              } %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/stacked_shell/nav/_desktop_nav.html.erb
<nav id="desktop-nav" class="border-b border-gray-700 bg-gray-800 lg:border-none">
  <div class="mx-auto max-w-7xl px-2 sm:px-4 lg:px-8">
    <div class="relative flex h-16 items-center justify-between lg:border-b lg:border-indigo-400 lg:border-opacity-25">
      <div class="flex items-center px-2 lg:px-0">
        <div class="flex-shrink-0">
          <div class="h-8 w-auto">

            <% navbar_brand_url = user_signed_in? ? dashboard_path : root_path %>
            <%= link_to "LMS", navbar_brand_url, class:"mt-0.5 text-slate-200 hover:text-slate-100 text-lg sm:text-xl lg:text-2xl inline-block h-8 w-auto" %>

          </div>
        </div>
        <div class="hidden lg:ml-10 lg:block">
          <div class="flex space-x-4">

            <% desktop_navigation_resource_css_classes = "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm" %>
            <% desktop_navigation_resource_css_classes_current = "bg-gray-900 text-white rounded-md px-3 py-2 text-sm font-medium" %>

            <%= render partial: "layouts/stacked_shell/nav/resource_links", locals:{
              resource_links_css_classes_current: desktop_navigation_resource_css_classes_current,
              resource_links_css_classes: desktop_navigation_resource_css_classes,
            } %>

          </div>
        </div>
      </div>
      <!-- search input -->
      <div class="flex flex-1 justify-center px-2 lg:ml-6 lg:justify-end">
        <div class="w-full max-w-lg lg:max-w-xs">
          <label for="search" class="sr-only">Search</label>
          <div class="relative text-gray-400 focus-within:text-gray-600">
            <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z" clip-rule="evenodd" />
              </svg>
            </div>

            <!--
            NOTE : search_input_placeholder_text (tmp) defined in: layouts/stacked_shell
           -->
            <input id="search" class="block w-full rounded-md border-0 bg-white py-1.5 pl-10 pr-3 text-gray-900 focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-indigo-600 sm:text-sm sm:leading-6" placeholder="<%= search_input_placeholder_text %>" type="search" name="search">

          </div>
        </div>
      </div>
      <div class="hidden lg:ml-4 lg:block">
        <div class="flex items-center">
          <div data-controller="visibility" data-visibility-value-toggled="false" class="relative ml-3 flex-shrink-0">
            <div>
              <button type="button"  data-action="visibility#toggleTargets" class="flex rounded-md bg-gray-800 text-sm text-gray-400 border-2 border-gray-400 transition ease-in-out delay-150 hover:scale-105 duration-100 hover:border-slate-100 p-1 hover:text-slate-100 hover:text-md focus:ring-1 focus:ring-slate-200 focus:ring-offset-slate-100" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                <span class="sr-only">Open user menu</span>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                </svg>
              </button>
            </div>
            <!--
              Dropdown menu, show/hide based on menu state.
              Entering: "transition ease-out duration-100"
                From: "transform opacity-0 scale-95"
                To: "transform opacity-100 scale-100"
              Leaving: "transition ease-in duration-75"
                From: "transform opacity-100 scale-100"
                To: "transform opacity-0 scale-95"
            -->
            <div data-visibility-target="hideable" hidden class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">

              <% profile_dropdown_navigation_css_classes = "block py-2 px-4 text-sm text-gray-500 hover:text-gray-600 hover:bg-slate-50" %>
              <% profile_dropdown_navigation_css_classes_current = "block py-2 px-4 text-sm text-gray-600 font-medium bg-slate-100" %>

              <%= render partial: "layouts/stacked_shell/nav/user_links", locals:{
                user_links_css_classes_current: profile_dropdown_navigation_css_classes_current,
                user_links_css_classes: profile_dropdown_navigation_css_classes,
              } %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/stacked_shell/nav/_mobile.html.erb
<nav id="mobile-nav" data-controller="visibility" data-visibility-value-toggled="false" class="border-b border-gray-700 bg-gray-800 lg:border-none">
  <div class="mx-auto max-w-7xl px-2 sm:px-4 lg:px-8">
    <div class="relative flex h-16 items-center justify-between lg:border-b lg:border-indigo-400 lg:border-opacity-25">
      <div class="flex items-center px-2 lg:px-0">
        <div class="flex-shrink-0">
          <div class="h-8 w-auto">
            <% navbar_brand_url = user_signed_in? ? dashboard_path : root_path %>
            <%= link_to "LMS", navbar_brand_url, class:"mt-0.5 text-slate-200 hover:text-slate-100 text-lg sm:text-xl lg:text-2xl inline-block h-8 w-auto" %>
          </div>
        </div>
      </div>

      <div class="flex flex-1 justify-center px-2 lg:ml-6 lg:justify-end">
        <div class="w-full max-w-lg lg:max-w-xs">
          <%= yield :search_bar %>
        </div>
      </div>

      <!-- Mobile menu button -->
      <div class="flex lg:hidden">
        <button type="button" data-action="visibility#toggleTargets" class="inline-flex items-center justify-center rounded-md bg-gray-800 p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>
  <div id="mobile-menu" data-visibility-target="hideable" hidden>
    <div class="space-y-1 px-2 pt-2 pb-3">

      <% mobile_navigation_resource_css_classes = "text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium" %>
      <% mobile_navigation_resource_css_classes_current = "bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium" %>

      <%= render partial: "layouts/stacked_shell/nav/resource_links", locals:{
        resource_links_css_classes_current: mobile_navigation_resource_css_classes_current,
        resource_links_css_classes: mobile_navigation_resource_css_classes,
      } %>

    </div>
    <div class="border-t border-gray-700 pt-4 pb-3">
      <div class="flex items-center px-5">
        <%# if user_signed_in? %>
        <!-- <div class="cursor-default text-md font-bold text-gray-500">
          Welcome <%#= "#{current_user.email}" %>
        </div> -->
        <!-- <button type="button" class="ml-auto flex-shrink-0 rounded-full bg-gray-800 p-1 text-indigo-200 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-indigo-600">
          <span class="sr-only">View notifications</span>
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
          </svg>
        </button> -->
        <%# end %>
      </div>
      <div class="mt-3 space-y-1 px-2">
        <div class="-mt-6">
          <!-- placeholder to adjust extra padding on top -->
        </div>
        <%= render partial: "layouts/stacked_shell/nav/user_links", locals:{
          user_links_css_classes_current: mobile_navigation_resource_css_classes_current,
          user_links_css_classes: mobile_navigation_resource_css_classes,
        } %>

      </div>
    </div>
  </div>
</nav>

app/views/layouts/stacked_shell/nav/_resource_links.html.erb
<% resource_links_css_classes = "" unless defined?(resource_links_css_classes) %>
<% resource_links_css_classes_current = "" unless defined?(resource_links_css_classes_current) %>

<% if current_user %>
  <%= link_to "Dashboard", dashboard_path, class: resource_links_css_classes_current if current_page?(dashboard_path) %>
  <%= link_to "Dashboard", dashboard_path, class: resource_links_css_classes if !current_page?(dashboard_path) %>

  <%= link_to "Orders", orders_path(status: 'active'), class: resource_links_css_classes_current if "orders".in? controller_path %>
  <%= link_to "Orders", orders_path(status: 'active'), class: resource_links_css_classes unless "orders".in? controller_path %>

  <%= link_to "Ships", purchasers_path, class: resource_links_css_classes_current if "purchasers".in? controller_path %>
  <%= link_to "Ships", purchasers_path, class: resource_links_css_classes if !"purchasers".in? controller_path %>

  <% if authorized_internal_user? %>
    <%= link_to "Vendors", vendors_path, class: resource_links_css_classes_current if "vendors".in? controller_path %>
    <%= link_to "Vendors", vendors_path, class: resource_links_css_classes if !"vendors".in? controller_path %>
  <% end %>
<% end %>

app/views/layouts/stacked_shell/nav/_secondary_nav.html.erb
<nav id="secondary-nav" class="rounded-t-md bg-slate-200 py-3  mx-auto px-4 sm:px-6 lg:px-8">
  <% if user_signed_in? %>
    <nav class="sm:hidden">
      <div class="text-gray-700 bg-white">
        <div data-controller="visibility" data-visibility-value-toggled="false" class="relative text-center">
         <button type="button" data-action="visibility#toggleTargets" class="bg-white hover:bg-gray-50 flex justify-center items-center w-full rounded-md p-2  text-md leading-6 font-semibold text-gray-700" aria-controls="sub-menu-1" aria-expanded="false">
           <% request_controller_class = request.controller_class.to_s %>
           <%= content_tag(:p, "Dashboard" ) if current_page?(dashboard_path) %>
           <%= content_tag(:p, "Orders" )  if (request_controller_class == "OrdersController")  %>
           <%= content_tag(:p, "Ships" ) if (request_controller_class == "PurchasersController") || (request_controller_class == "Purchasers::OrdersController") %>
           <%= content_tag(:p, "Vendors" ) if authorized_internal_user? && (request_controller_class == "VendorsController") || (request_controller_class == "Vendors::OrdersController") %>
         </button>
         <div data-visibility-target="hideable" hidden class="mt-1" id="sub-menu-1">
           <% mobile_navigation_resource_css_classes = "hover:bg-gray-50 block rounded-md py-2  text-sm leading-6 text-gray-700" %>
           <% mobile_navigation_resource_css_classes_current = "hover:bg-gray-50 block rounded-md py-2  text-sm leading-6 text-gray-700" %>
           <%= link_to "Dashboard", dashboard_path, class: mobile_navigation_resource_css_classes unless current_page?(dashboard_path) %>
           <%= link_to "Orders", orders_path(status: "active"), class: mobile_navigation_resource_css_classes unless (request_controller_class == "OrdersController") %>
           <%= link_to "Ships", purchasers_path, class: mobile_navigation_resource_css_classes unless (request_controller_class == "PurchasersController") || (request_controller_class == "Purchasers::OrdersController") %>
           <% if authorized_internal_user? %>
             <%= link_to "Vendors", vendors_path, class: mobile_navigation_resource_css_classes if !"vendors".in? controller_path %>
          <% end %>
         </div>
       </div>
      </div>
    </nav>
  <% end %>
  <div class="hidden sm:block">
    <div class="flex justify-between">
      <nav class="flex space-x-4 inline-flex" aria-label="Tabs">
        <% secondary_desktop_navigation_resource_css_classes = "text-gray-600 hover:text-gray-900 hover:bg-gray-50 hover:border-gray-200 rounded-md px-3 py-2 text-sm font-medium" %>
        <% secondary_desktop_navigation_resource_css_classes_current = "bg-slate-50 text-gray-900 rounded-md px-3 py-2 text-sm font-semibold"  %>
        <%= render partial: "layouts/stacked_shell/nav/resource_links", locals:{
          resource_links_css_classes_current: secondary_desktop_navigation_resource_css_classes_current,
          resource_links_css_classes: secondary_desktop_navigation_resource_css_classes,
        } %>
      </nav>
      <div class="flex flex-wrap inline-flex hover:cursor-default">
        <%= user_badge %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/stacked_shell/nav/_user_links.html.erb
<% user_links_css_classes = "" unless defined?(user_links_css_classes) %>
<% user_links_css_classes_current = "" unless defined?(user_links_css_classes_current) %>

<% if current_user %>
  <div class="<%= user_links_css_classes %> divide-y divide-gray-200 lg:py-1 rounded-none border-b border-gray-700 lg:border-gray-200">
    <div class="font-bold lg:text-center cursor-default">
      Hello <%= current_user.email %>
    </div>
  </div>

  <%= link_to "Admin Dashboard", admin_users_path, class: user_links_css_classes if current_user.has_role? :admin %>
  <%#= link_to "App Service Links", directory_links_path, class: user_links_css_classes if current_user.has_role? :admin %>

  <%#= link_to "Account Settings", edit_user_registration_path, class: user_links_css_classes_current if current_page?(edit_user_registration_path) %>
  <%#= link_to "Account Settings", edit_user_registration_path, class: user_links_css_classes if !current_page?(edit_user_registration_path) %>

  <%#= link_to "Logout", destroy_user_session_path, method: :delete, class: user_links_css_classes %>
  <div class="<%= user_links_css_classes %>">
  <%= button_to(
        "Logout",
        destroy_user_session_path,
        method: :delete,
      ) %>
  </div>

<% end %>

<% if !current_user %>
  <%= link_to "Home", root_path, class: user_links_css_classes_current if current_page?(root_path) %>
  <%= link_to "Home", root_path, class: user_links_css_classes if !current_page?(root_path) %>

  <%= link_to "Sign In", new_user_session_path, class: user_links_css_classes_current if current_page?(new_user_session_path) %>
  <%= link_to "Sign In", new_user_session_path, class: user_links_css_classes if !current_page?(new_user_session_path) %>
<% end %>